name: Run Cypress Tests

on:
  schedule:
    # * is a wildcard that matches any value
    # This will run every 20 minutes
    - cron: '*/20 * * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the version of Node.js that you need

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:run # This should be the command to run your Cypress tests
